spring.application.name=aitken-junior

logging.pattern.level=%d{yyyy-MM-dd-HH:mm:ss} - [%X{correlationId}] - %5p - %msg

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:31971/postgres
spring.datasource.username=postgres
spring.datasource.password=temp_test_password