name: MVN Verify
on:
  push:
    branches: [ main ] # Runs on pushes to default branch
  pull_request:
    branches: [ main ] # Runs on any PRs to default branch

jobs:
  verify:
    name: MVN Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23 # Same JAVA Version as machine
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run MVN Verify
        run: mvn verify
