name: MVN Verify
run-name: ${{ github.actor }} is running Verification
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribuition: 'temurin'
          cache: maven
      - name: Run MVN Verify
        run: mvn verify
